name = "JuliaRegistry"
uuid = "e0596c06-ee51-4ff2-959e-bf52646bff5c"
repo = "https://github.com/henrij22/JuliaRegistry.git"
description = "Julia Registry"

[packages]
15d96d4e-a55c-433f-b8eb-a88007b7373b = { name = "MuesliMaterials", path = "M/MuesliMaterials" }
402afd0f-a347-4f14-ad4c-abedc99e1684 = { name = "PyVistaCompat", path = "P/PyVistaCompat" }
5750890c-44ac-400c-9e9d-1788b5a8ead6 = { name = "TinyGismo", path = "T/TinyGismo" }
61c3bbe5-5a69-4256-958a-2912b3f39d32 = { name = "EigenValueSolvers", path = "E/EigenValueSolvers" }
6dead231-e870-550e-b74b-2a3bf2cfaa53 = { name = "MuesliMaterialsWrapper_jll", path = "jll/M/MuesliMaterialsWrapper_jll" }
7e61441e-6e6e-5c6f-8c66-76107880e13d = { name = "TinyGismo_jll", path = "jll/T/TinyGismo_jll" }
a548586d-644c-43c2-b402-969e06ddf6f5 = { name = "FerriteGismo", path = "F/FerriteGismo" }
