name = "JuliaRegistry"
uuid = "e0596c06-ee51-4ff2-959e-bf52646bff5c"
repo = "https://github.com/henrij22/JuliaRegistry.git"
description = "Julia Registry"

[packages]
402afd0f-a347-4f14-ad4c-abedc99e1684 = { name = "PyVistaCompat", path = "P/PyVistaCompat" }
ef259003-9f3a-5fc7-ae68-dce6b88dc7d6 = { name = "MuesliMaterials_jll", path = "jll/M/MuesliMaterials_jll" }
